repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: python -m pytest
        language: system
        always_run: true
        stages: [push]
